name: Bubble
version: ${project.version}
main: me.markings.bubble.Bubble
api-version: 1.13
libraries:
  - org.openjdk.nashorn:nashorn-core:15.3
softdepend: [ AuthMe, BanManager, BungeeChatAPI, CMI, DiscordSRV, Factions, Feudal, ItemsAdder, Essentials, LegacyFactions, Lands, LuckPerms, Multiverse-Core, MVdWPlaceholderAPI, MythicMobs, mcMMO, NashornPlus, Nicky, PlaceholderAPI, ProtocolLib, SimpleClans, Towny, TownyChat, Vault, WorldEdit ]
authors: [ Markings ]
description: An easy, powerful, and customizable notifications and chat tool for Minecraft servers.